---
title: "PLAY Session Spreadsheet QA"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: 
  html_document:
    keep_md: true
    theme: lumen
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: hide
params:
  vol_id: 899
  databrary_login: account@email.com
  site_code: NYU
  only_show_included: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

db_login_ok <- databraryapi::login_db(params$databrary_login)
if(db_login_ok) {
  message("Databrary authentication successful.")
}

source("R/qa_report_helpers.R")

library(tidyverse)
```

# PLAY Site `r params$site_code` QA Report

Site data collection volume: <`r paste0("https://databrary.org/volume/", params$vol_id)`>

## Session name checks

```{r}
this_vol_df <- databraryapi::download_session_csv(params$vol_id)

this_vol_df <- this_vol_df %>%
  dplyr::arrange(., desc(session_date))

name_checks_l <- lapply(1:dim(this_vol_df)[1], check_session_name, this_vol_df, params$site_code)
name_checks <- Reduce(function(x,y) merge(x,y, all=TRUE), name_checks_l)
```

```{r}
name_checks_fmt <- name_checks %>%
  dplyr::mutate(., 
  has_PLAY = kableExtra::cell_spec(
    has_PLAY,
    "html",
    color = ifelse(has_PLAY == TRUE, "green", "red")),
  has_site_id = kableExtra::cell_spec(
    has_site_id,
    "html",
    color = ifelse(has_site_id == TRUE, "green", "red")),
  has_sub_id = kableExtra::cell_spec(
    has_sub_id,
    "html",
    color = ifelse(has_sub_id == TRUE, "green", "red")),
  has_corr_seps = kableExtra::cell_spec(
    has_corr_seps,
    "html",
    color = ifelse(has_corr_seps == TRUE, "green", "red")),
  play_id_valid = kableExtra::cell_spec(
    play_id_valid,
    "html",
    color = ifelse(play_id_valid == TRUE, "green", "red")),
  length_ok = kableExtra::cell_spec(
    length_ok,
    "html",
    color = ifelse(length_ok == TRUE, "green", "red"))
    )
```

```{r}
name_checks_fmt[,1:5] %>%
  knitr::kable(., format = "html", escape = FALSE) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r}
name_checks_fmt[,c(1, 6:dim(name_checks)[2])] %>%
   knitr::kable(., format = "html", escape = FALSE) %>%
   kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

## Session spreadsheet variable checks

```{r}
ss_checks_l <- lapply(1:dim(this_vol_df)[1], check_session_ss, this_vol_df, params$site_code)
ss_checks <- Reduce(function(x,y) merge(x,y, all=TRUE), ss_checks_l)
```

```{r}
ss_checks_fmt <- ss_checks %>%
  dplyr::mutate(.,
                release_level_ok = kableExtra::cell_spec(
                  release_level_ok,
                  "html",
                  color = ifelse(release_level_ok == TRUE, "green", "red")
                )) %>%
  dplyr::mutate(.,
                release_level_public = kableExtra::cell_spec(
                  release_level_public,
                  "html",
                  color = ifelse(release_level_public == TRUE, "red", "green")
                )) %>%
  dplyr::mutate(.,
                birth_before_test = kableExtra::cell_spec(
                  birth_before_test,
                  "html",
                  color = ifelse(birth_before_test == TRUE, "green", "red")
                )) %>%
  dplyr::mutate(.,
                test_after_start = kableExtra::cell_spec(
                  test_after_start,
                  "html",
                  color = ifelse(test_after_start == TRUE, "green", "red")
                )) %>%
  dplyr::mutate(.,
                age_group_valid = kableExtra::cell_spec(
                  age_group_valid,
                  "html",
                  color = ifelse(age_group_valid == TRUE, "green", "red")
                )) %>%
  dplyr::mutate(.,
                gender_ok = kableExtra::cell_spec(gender_ok,
                "html",
                color = ifelse(gender_ok == TRUE, "green", "red"))) %>%
  dplyr::mutate(., 
                race_ok = kableExtra::cell_spec(race_ok,
                "html",
                color = ifelse(race_ok == TRUE, "green", "red"))) %>%
  dplyr::mutate(.,
                ethnicity_ok = kableExtra::cell_spec(
                  ethnicity_ok,
                  "html",
                  color = ifelse(ethnicity_ok == TRUE, "green", "red")
                )) %>%
  dplyr::mutate(.,
                disability_ok = kableExtra::cell_spec(
                  disability_ok,
                  "html",
                  color = ifelse(disability_ok == TRUE, "green", "red")
                )) %>%
  dplyr::mutate(.,
                language_ok = kableExtra::cell_spec(
                  language_ok,
                  "html",
                  color = ifelse(language_ok == TRUE, "green", "red"))) %>%
  dplyr::mutate(.,
                exclusion_ok = kableExtra::cell_spec(
                  exclusion_ok,
                  "html",
                  color = ifelse(exclusion_ok == TRUE, "green", "red")
                )) %>%
  dplyr::mutate(.,
                not_excluded = kableExtra::cell_spec(
                  not_excluded,
                  "html",
                  color = ifelse(not_excluded == TRUE, "green", "red")
                )) %>%
  dplyr::mutate(., 
                home_ok = kableExtra::cell_spec(home_ok,
                "html",
                 color = ifelse(home_ok == TRUE, "green", "red"))) %>%
  dplyr::mutate(., 
                country_ok = kableExtra::cell_spec(country_ok,
                "html",
                color = ifelse(country_ok == TRUE, "green", "red"))) %>%
  dplyr::mutate(., 
                state_ok = kableExtra::cell_spec(state_ok,
                "html",
                color = ifelse(state_ok == TRUE, "green", "red")))
```

```{r}
ss_checks_fmt[, 1:5] %>%
  knitr::kable(., format = "html", escape = FALSE) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r}
ss_checks_fmt[, c(1, 6:10)] %>%
  knitr::kable(., format = "html", escape = FALSE) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r}
ss_checks_fmt[,c(1, 11:dim(ss_checks_fmt)[2])] %>%
  knitr::kable(., format = "html", escape = FALSE) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

## Video file-level checks

```{r}
check_videos_l <- lapply(1:dim(this_vol_df)[1], check_videos_in_session, this_vol_df, params$vol_id)
check_videos_df <- Reduce(function(x,y) merge(x,y, all=TRUE), check_videos_l)
```

```{r}
check_videos_fmt <- check_videos_df %>%
  dplyr::mutate(NaturalPlay_exists = kableExtra::cell_spec(
    NaturalPlay_exists,
    "html",
    color = ifelse(NaturalPlay_exists == TRUE, "green", "red")
  ),
  HouseWalkthrough_exists = kableExtra::cell_spec(
    HouseWalkthrough_exists,
    "html",
    color = ifelse(HouseWalkthrough_exists == TRUE, "green", "red")
  ),
  StructuredPlay_exists = kableExtra::cell_spec(
    StructuredPlay_exists,
    "html",
    color = ifelse(StructuredPlay_exists == TRUE, "green", "red")
  ),
  Questionnaires_exists = kableExtra::cell_spec(
    Questionnaires_exists,
    "html",
    color = ifelse(Questionnaires_exists == TRUE, "green", "red")
  ),
  four_or_more_videos = kableExtra::cell_spec(
    four_or_more_videos,
    "html",
    color = ifelse(four_or_more_videos == TRUE, "green", "red")
  ))
```

```{r}
check_videos_fmt[, 1:4] %>%
  knitr::kable(., format = "html", escape = FALSE) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r}
check_videos_fmt[, c(1, 5:dim(check_videos_fmt)[2])] %>%
  knitr::kable(., format = "html", escape = FALSE) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```
