---
title: "user-stories"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: 
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: hide
---

## User stories

### Workflow creation

As a volume owner, I want to create a workflow for a project. 
A workflow is a sequence of operations consisting of people, tasks or sub-tasks, and files. 
A workflow also consists of conditions which determine how information flows within the sequence of operations. 
For example, if a file passes Quality Assurance review it is assigned to the Coding Queue. 
If the file fails Quality Assurance review, it is assigned to a Curate Other Data queue.

As a volume owner creating a workflow, I want to create queues or ordered lists of files of a specific type that are awaiting human action in a workflow. 
Queues have a first-in-first out structure unless there is a priority override associated with a given file. 

As a volume owner or task manager, I want to create a priority override for a given file or files in a workflow. 
The priority override puts the designated files at the top of the queue, overriding the normal first-in-first out ordering of files/tasks in a queue.

As a volume owner creating a workflow, I want to create a list of tasks (analogous to epics in Agile methodology) that are linked to one another in an orderly sequence. 
For example, the figure above shows that Data Collection (e.g., by one of the 30 PLAY collection sites) is a task that is followed by Quality Assurance. 
Quality Assurance is followed by either Assignment to Coding or to Transfer to PLAY-other data volume on Databrary.

As a volume owner creating a workflow, I want to assign ownership over a task to a task manager. 
For example, a volume owner can designate a Quality Assurance manager for that particular task.

As a volume owner creating tasks or task manager, I want to create sequences of sub-tasks. 

For example, the Quality Assurance task might consist of the following sub-tasks: Assign video X to QA Analyst for review, Assign metadata X to QA analyst for review, Review QA Analyst report on video X, Review QA Analyst report on metadata X, Assign video X to coding queue, Assign video X to Curate other data queue.

Sub-tasks consist of the task description, an assigned person, status information, and the file names/identifiers, e.g., video file X or metadata file X.

As a volume owner or task manager, I want to be able to create volumes co-owned with specific coding lab PIs. 
The volumes will be linked to my workflows.

### Training

As a member of the PLAY staff, I need to assign specific data collection labs and data coding labs to general training tasks (use of LabNanny, use of Databrary), collection training tasks (scheduling & intake, video & survey data collection, cleanup & data entry), and coding training tasks (use of Datavyu, specific coding pass)

### Data Collection

As a volume owner or task manager, I want to be able to assign a data collection session to a data collection lab queue. 
The data collection session includes a participant code in the form of <site-id>-<participant-id> and may also include recommendations about the race/ethnicity, gender, or other demographic characteristics of the participant. 
For example, site and participant ID’s will be 4 digit numbers, making 0001-0001 a valid participant code. 

We should probably include the Databrary volume/session (slot) IDs in the metadata, perhaps in the file names themselves. 
This will make it easier to map project related info (sites and participant IDs) with the Databrary backend.

As a volume owner or task manager, I want to be able to create sessions in a volume for each data collection session assigned to a data collection lab queue. 
The volume I create will be co-owned with the data collection lab PI. The session will be populated with the site and participant IDs generated by Databrary. 
A new field will be added to the volume spreadsheet indicating the session’s data collection status.

As a data collection lab PI, I want to be to view my data collection queue; I want to be able to assign a data collection session in that queue to my lab scheduler.

As a data collection lab PI, once I have confirmed a participant family’s data collection session I want to enter in participant information that can be propagated across all of files, workflows, and coding for this participant family. 
This information includes sensitive contact information, demographics, age, disability status/eligibility to participate. Assign an anonymized participant ID that follows everything related to this participant. 
Some information (participant contact information, specifics of names) will only be visible to that data collection lab PI; all non-contact information is visible to all other labs.

As a data collection lab PI, once I have entered participant information and assigned a participant ID, when I am ready to go on a data collection session, I want to be able to automatically populate pdf forms that will be taken on the data collection and fill them with all of the information related to participant information.

### Data Uploading

As a data collection lab PI or my designated lab manager, I want to be able to upload video files, questionnaire data files, and other files to a specific data collection session. 
If the data collection session is 

### Quality Assurance (QA) review

As a data collection lab PI, I want to be able to upload video and other files to a data collection session on Databrary.

If/when we adopt a standard directory format for data collection sessions like BIDS we can modify this so that data collection lab PIs put their video and other files in the specified directory structure. For example: 0001-0001/0001-0001.mp4 and 0001-0001.questionnaires.mp4, etc. 
Then, the desktop sync can do the uploading to the centrally-generated volume & spreadsheet.

As a member of the PLAY staff I want to be able to prioritize that a data collection session from a new data collection lab, needs to be vetted for quality assurance before other files that need to be vetted for QA. 
(Details of which data collection lab have been vetted for quality data collection, need to be tracked and viewable separately in a list of trained/reliable data collection labs.)

### Coding passes

As a volume owner or task manager, I want to add a video for a specific coding pass to a specific coding lab queue. 
Adding a video to a coding lab queue for a coding pass generates a Datavyu coding template file customized for the video and pass. 
The Datavyu coding template file is added to the coding lab queue along with the video.

The Datavyu coding file template is a Datavyu file with a file name assigned by Databrary in the format of <site-id>-<video-id>-<pass-id>, an initial <id> spreadsheet column with <participant-id> and <age-group> variables only, and a column specific to the type of coding pass, e.g., transcription, language, gesture, emotional expression, locomotion, or object interaction.

As a coding lab PI, I want to assign a video assigned to my coding lab queue to a specific coder.

As a coding lab PI, want to be able to view a coding lab dashboard for my lab. 
The coding lab dashboard shows me the status of all videos in my coding lab queue, including those that have not yet been assigned to a coder, those that have been assigned to a coder and are in-process, those that have been coded, those that have been added to the interobserver reliability queue, those that have passed interobserver reliability review, and those that have been returned for recoding.

As a member of the PLAY staff I want to be able to prioritize that a coding pass from a new coder or new coding lab, needs to be vetted for interobserver reliability before other files that need to be vetted for reliability. 
(Details of which coding lab and coders have been vetted for reliable coding, need to be tracked and viewable separately in a list of trained/reliable coding labs/coders.)

### Data Sharing

As a volume owner or task manager, I want to assign data packages for sharing QA review to the sharing QA queue.

### Analytics/Viewing/Monitoring

As a volume owner or task manager I want to monitor progress in my workflow via analytics.

As a member of the PLAY staff, I want to view all participant IDs (participant-associated files) that are within a certain phase (ready for data collection, data collection complete, QA complete, data coding needs to be assigned, data coding in progress, data coding complete, data reliability needs to be assigned, data reliability in progress, fully coded and reliable, did not pass QA, did not pass reliability). 
The level of detail of viewing, needs to be about what needs to be done across all participants, NOT which individual person has been assigned what tasks.

As a member of the PLAY staff, I want to view what aspects of training/reliability need explicit attention within a data collection lab or data coding lab. 
I need to be able to view which labs are “good to go” for each aspect of collection or coding, and which need to revetted and need to be retrained. 
Aspects of training/vetting for data collection include: identifying eligible participants, scheduling/confirming, video collection, survey collection, data entry. 
Aspects of training/vetting for data coding include: initial training.
